# All messages are configured in messages.yml, this config is used to change the values nesecarry for the MySQL Functionality to work
Database-URL: https://example.com/
Database-User: admin
Databale-Passworld: password